# ==================
# Project Details
# ==================
name: "Onbe_CICD_Demo"
config-version: 2
require-dbt-version:
- ">=1.0.0"
- "<2.0.0"
version: "0.2.14"
profile: "run_profile_snowflake"

# ==================
# File Path Configs
# ==================
test-paths:
- "tests"
clean-targets:
- "target"
- "dbt_modules"
- "logs"
seed-paths:
- "seeds"
model-paths:
- "models"
- "prophecy-sources"
analysis-paths:
- "analysis"
macro-paths:
- "macros"
target-path: "target"

# ==================
# Variable Configs
# ==================
vars:
  env: "{DEV,PROD}"

# ==================
# Model Configs
# ==================
models:
  Onbe_CICD_Demo:
    materialized: "table"
    staging:
      materialized: "view"

# ============
# Misc
# ============
dispatch: []
