name: Onbe_CICD_Demo
description: ''
version: 0.3.1
author: null
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/run_all:
    name: run-all-dev
    description: ''
    fabricUID: 22701
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0/1 * * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: false
    createdAt: '2025-02-27 16:33:18'
    author: best.neil@prophecy.io
    models: []
    sqlProjects:
    - '42856'
  jobs/run-all-prod:
    name: run-all-prod
    description: ''
    fabricUID: 22701
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0/1 * * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: false
    createdAt: '2025-03-03 19:11:35'
    author: best.neil@prophecy.io
    models: []
    sqlProjects:
    - '42856'
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-08-05 08:34:32'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/stg_orders:
    name: stg_orders
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: ORDER_ID
        dataType:
          type: Number
      - name: CUSTOMER_ID
        dataType:
          type: Number
      - name: ORDER_DATE
        dataType:
          type: Date
      - name: STATUS
        dataType:
          type: String
    description: null
    author: kiranadmin@prophecy.io
    files:
    - models/staging/stg_orders.sql
    - .prophecy/ide/models/stg_orders.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-08-05 08:36:43'
  .prophecy/metadata/sqlmodels/orders:
    name: orders
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: ORDER_ID
        dataType:
          type: Number
      - name: CUSTOMER_ID
        dataType:
          type: Number
      - name: ORDER_DATE
        dataType:
          type: Date
      - name: STATUS
        dataType:
          type: String
      - name: CREDIT_CARD_AMOUNT
        dataType:
          type: Number
      - name: COUPON_AMOUNT
        dataType:
          type: Number
      - name: BANK_TRANSFER_AMOUNT
        dataType:
          type: Number
      - name: GIFT_CARD_AMOUNT
        dataType:
          type: Number
      - name: AMOUNT
        dataType:
          type: Number
    description: This table has basic information about orders, as well as some derived
      facts based on payments
    author: kiranadmin@prophecy.io
    files:
    - models/orders.sql
    - .prophecy/ide/models/orders.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-08-05 08:36:43'
  .prophecy/metadata/sqlmodels/customers:
    name: customers
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: CUSTOMER_ID
        dataType:
          type: Number
      - name: FIRST_NAME
        dataType:
          type: String
      - name: LAST_NAME
        dataType:
          type: String
      - name: FIRST_ORDER
        dataType:
          type: Date
      - name: MOST_RECENT_ORDER
        dataType:
          type: Date
      - name: NUMBER_OF_ORDERS
        dataType:
          type: Number
      - name: CUSTOMER_LIFETIME_VALUE
        dataType:
          type: Number
    description: This table has basic information about a customer, as well as some
      derived facts based on a customer's orders
    author: kiranadmin@prophecy.io
    files:
    - models/customers.sql
    - .prophecy/ide/models/customers.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-08-05 08:36:43'
  .prophecy/metadata/sqlmodels/stg_payments:
    name: stg_payments
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: PAYMENT_ID
        dataType:
          type: Number
      - name: ORDER_ID
        dataType:
          type: Number
      - name: PAYMENT_METHOD
        dataType:
          type: String
      - name: AMOUNT
        dataType:
          type: Number
    description: null
    author: kiranadmin@prophecy.io
    files:
    - models/staging/stg_payments.sql
    - .prophecy/ide/models/stg_payments.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-08-05 08:36:43'
  .prophecy/metadata/sqlmodels/stg_customers:
    name: stg_customers
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: CUSTOMER_ID
        dataType:
          type: Number
      - name: FIRST_NAME
        dataType:
          type: String
      - name: LAST_NAME
        dataType:
          type: String
    description: null
    author: kiranadmin@prophecy.io
    files:
    - models/staging/stg_customers.sql
    - .prophecy/ide/models/stg_customers.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-08-05 08:36:43'
sqlSnapshots: {}
sqlTests:
  .prophecy/metadata/sqltests/count_records:
    name: count_records
    description: null
    author: best.neil@prophecy.io
    files:
    - tests/generic/count_customers.sql
    testType: GenericDataTest
    createdAt: '2025-03-10 19:16:52'
sqlMacros:
  .prophecy/metadata/sqlmacros/generate_schema_name:
    name: generate_schema_name
    macroType: expression
    description: null
    author: kiranadmin@prophecy.io
    files:
    - macros/generate_schema_name.sql
    - .prophecy/ide/macros/generate_schema_name.json
    createdAt: '2024-08-05 08:39:54'
sqlSeeds:
  .prophecy/metadata/sqlseeds/raw_customers:
    name: raw_customers
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: id
        dataType:
          type: Number
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: kiranadmin@prophecy.io
    files:
    - seeds/raw_customers.csv
    createdAt: '2024-08-05 08:36:43'
  .prophecy/metadata/sqlseeds/raw_orders:
    name: raw_orders
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: id
        dataType:
          type: Number
      - name: user_id
        dataType:
          type: Number
      - name: order_date
        dataType:
          type: Date
      - name: status
        dataType:
          type: String
    description: null
    author: kiranadmin@prophecy.io
    files:
    - seeds/raw_orders.csv
    createdAt: '2024-08-05 08:36:43'
  .prophecy/metadata/sqlseeds/raw_payments:
    name: raw_payments
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: id
        dataType:
          type: Number
      - name: order_id
        dataType:
          type: Number
      - name: payment_method
        dataType:
          type: String
      - name: amount
        dataType:
          type: Number
    description: null
    author: kiranadmin@prophecy.io
    files:
    - seeds/raw_payments.csv
    createdAt: '2024-08-05 08:36:43'
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: kiranadmin@prophecy.io
  createdAt: '2024-08-05 08:34:32'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
